---
title: "RRASSLER Data Formats"
output: rmarkdown::html_vignette
description: |
  "What form of data are we after?"
vignette: >
  %\VignetteIndexEntry{data-format}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(dm)
library(labelled)
```

# Full Data Model

Once RRASSLER processing has been run all the way through, the data generated will have the following schema, matching as closely as possible the standard HEC-RAS cross section data format:

```{r, echo = FALSE}
ras_dbase <- fs::path_package("/extdata/sample_output/ras_catalog/", package = "RRASSLER")

model_footprints.fgb <- sf::st_read(file.path(ras_dbase,"model_footprints.fgb",fsep = .Platform$file.sep),quiet=TRUE)
point_database.parquet <- arrow::open_dataset(file.path(ras_dbase,"point_database.parquet",fsep = .Platform$file.sep)) |> head(5) |> dplyr::collect()
XS.fgb <- sf::st_read(file.path(ras_dbase,"XS.fgb",fsep = .Platform$file.sep),quiet=TRUE)
accounting.csv <- data.table::fread(file.path(ras_dbase,"accounting.csv",fsep = .Platform$file.sep))
OWP_ras_models_catalog.csv <- data.table::fread(file.path(ras_dbase,"OWP_ras_model_catalog.csv",fsep = .Platform$file.sep))

single_model_path <- file.path(ras_dbase,"models","5789080_ALUM 107_g01_1691071096",fsep = .Platform$file.sep) # Could be a bit more programmatic...
RRASSLER_hull.fgb <- sf::st_read(file.path(single_model_path,"RRASSLER_hull.fgb",fsep = .Platform$file.sep),quiet=TRUE)
RRASSLER_cs_pts.parquet <- arrow::open_dataset(file.path(single_model_path,"RRASSLER_cs_pts.parquet",fsep = .Platform$file.sep)) |> head(5) |> dplyr::collect()
RRASSLER_river.fgb <- sf::st_read(file.path(single_model_path,"RRASSLER_river.fgb",fsep = .Platform$file.sep),quiet=TRUE)
RRASSLER_metadata.csv <- data.table::fread(file.path(single_model_path,"RRASSLER_metadata.csv",fsep = .Platform$file.sep))

my_dat <- dm::dm(model_footprints.fgb,
                 point_database.parquet,
                 XS.fgb,
                 accounting.csv,
                 OWP_ras_models_catalog.csv,
                 RRASSLER_hull.fgb,
                 RRASSLER_cs_pts.parquet,
                 RRASSLER_river.fgb,
                 RRASSLER_metadata.csv)

my_dat |>
  dm::dm_set_table_description(
    "Hulls of cross section lines in a single feature" = model_footprints.fgb,
    "XYZ tables of each station/elevation across the database" = point_database.parquet,
    "Cross sections" = XS.fgb,
    "A rollup catalog of all the models in the database" = accounting.csv,
    "A catalog appended with helper fields that aid in the downstream accounting at OWP " = OWP_ras_models_catalog.csv,
    "Hulls of cross section lines for a single model's geometric realization" = RRASSLER_hull.fgb,
    "XYZ tables of each station/elevation for that model" = RRASSLER_cs_pts.parquet,
    "River line extraction for the model" = RRASSLER_river.fgb,
    "Relevant model metadata in an easily accessible form" = RRASSLER_metadata.csv
  ) |>
  dm::dm_add_pk(model_footprints.fgb, final_name_key) |>
  dm::dm_add_pk(accounting.csv, final_name_key) |>
  dm::dm_add_pk(OWP_ras_models_catalog.csv, final_name_key) |>
  dm::dm_add_fk(accounting.csv, final_name_key, model_footprints.fgb, final_name_key) |>
  dm::dm_add_fk(model_footprints.fgb, final_name_key, accounting.csv, final_name_key) |>
  dm::dm_add_fk(accounting.csv, final_name_key, OWP_ras_models_catalog.csv, final_name_key) |>
  dm::dm_add_fk(OWP_ras_models_catalog.csv, final_name_key, accounting.csv, final_name_key) |>
  dm::dm_add_pk(point_database.parquet, master_id) |>
  dm::dm_add_pk(XS.fgb, master_id) |>
  dm::dm_add_fk(point_database.parquet, master_id, XS.fgb, master_id) |>
  dm::dm_add_fk(XS.fgb, master_id, point_database.parquet, master_id) |>
  dm::dm_add_fk(model_footprints.fgb, start_master_id, XS.fgb, master_id) |>
  dm::dm_add_fk(model_footprints.fgb, end_master_id, XS.fgb, master_id) |>
  dm::dm_add_pk(RRASSLER_metadata.csv, final_name_key) |>
  dm::dm_add_fk(RRASSLER_metadata.csv, final_name_key, accounting.csv, final_name_key) |>
  dm::dm_add_fk(RRASSLER_hull.fgb, geometry, model_footprints.fgb, geometry) |>
  dm::dm_add_fk(RRASSLER_cs_pts.parquet, xid, point_database.parquet, xid) |>
  # dm::dm_add_fk(model_footprints.fgb, path, OWP_ras_models_catalog.csv, final_name_key) |>
  # dm::dm_add_fk(OWP_ras_models_catalog.csv, final_name_key, model_footprints.fgb, path) |>
  dm::dm_set_colors(
    'coral' = RRASSLER_river.fgb,
    'coral' = RRASSLER_hull.fgb,
    'coral' = RRASSLER_cs_pts.parquet,
    'goldenrod' = XS.fgb,
    'goldenrod' = model_footprints.fgb,
    'goldenrod' = point_database.parquet,
    'burlywood' = OWP_ras_models_catalog.csv,
    'goldenrod' = accounting.csv,
    'coral' = RRASSLER_metadata.csv,
  ) |>
  dm::dm_draw(view_type = 'all')
```

```{r, echo = FALSE}
meta = tibble::tribble(
  ~Attribute, ~Description, ~Table,
  "id","A table specific id, otherwise meaningless","RRASSLER_hull.fgb, model_footprints.fgb, XS.fgb",
  "nhdplus_comid","The nhdplus comid from the 'primary downstream divergence' of the intersection of RRASSLER_hull.fgb, from nhdplusTools","RRASSLER_metadata.csv, accounting.csv, OWP_ras_models_catalog.csv",
  "geometry","Simple Features Geometry (LINESTRING or POLYGON)","RRASSLER_hull.fgb, RRASSLER_river.fgb, model_footprints.fgb",
  "master_id","A database specific ID for a cross section","XS.fgb",
  "start_master_id","The starting 'master_id' from the cross section database for that model","model_footprints.fgb",
  "end_master_id","The ending 'master_id' from the cross section database for that model","model_footprints.fgb",
  "model_name","The name of the model as provided by the filename","RRASSLER_metadata.csv, accounting.csv, model_footprints.fgb, OWP_ras_models_catalog.csv",
  "g_file","The particular geometric realization of the model","RRASSLER_metadata.csv, accounting.csv, OWP_ras_models_catalog.csv",
  "units","The units of the parent model","RRASSLER_metadata.csv, accounting.csv,OWP_ras_models_catalog.csv",
  "crs","The CRS of the parent model","RRASSLER_metadata.csv, accounting.csv, OWP_ras_models_catalog.csv",
  "initial_scrape_name","The first final_name_key RRASSLER assigns to the model, used for tracking","RRASSLER_metadata.csv, accounting.csv, OWP_ras_models_catalog.csv",
  "final_name_key","The primary key across the database, defines the path of the data","RRASSLER_metadata.csv, accounting.csv, model_footprints.fgb, OWP_ras_models_catalog.csv",
  "xid","A model specific cross section ID","RRASSLER_cs_pts.parquet, point_database.parquet",
  "xid_length","The length of the cross section","RRASSLER_cs_pts.parquet, point_database.parquet",
  "xid_d","The distance of the cross section down the parent stream model","RRASSLER_cs_pts.parquet, point_database.parquet",
  'relative_dist',"Distance of cs_id, starting at 0, in meters","point_database.parquet",
  'x',"X coordinate in EPSG:6349","point_database.parquet",
  'y',"Y coordinate in EPSG:6349","point_database.parquet",
  'z',"Z coordinate in EPSG:6349","point_database.parquet",
  'source',"Source of elevation data, encoded per purpose","point_database.parquet, RRASSLER_cs_pts.parquet",
  'source',"Source of the model provider","RRASSLER_metadata.csv, accounting.csv, OWP_ras_models_catalog.csv",
  'n',"Manning's roughness value","point_database.parquet",
  "last_modified","The date the ras model was last edited","accounting.csv, OWP_ras_models_catalog.csv",
  "notes","Summary notes and messages accumulated during processing, outputs delineated with a '*'","RRASSLER_metadata.csv, accounting.csv, OWP_ras_models_catalog.csv",
  "date","A human readable data of last processing","OWP_ras_models_catalog.csv",
  "hucs","A pythonically formatted list (braces and comma separated) that includes each HUC8 that the model intersects","OWP_ras_models_catalog.csv",
  "status","Status column set for downstream RAS2FIM processing","OWP_ras_models_catalog.csv",
)

formattable::formattable(meta)
```

Follow the [ingest steps](https://NOAA-OWP.github.io/RRASSLER/articles/ingest-steps.html) article to learn how RRASSLER processes a model to generate this data.
